[package]
name = "a32emu"
version = "0.4.2"
edition = "2021"
authors = [ "Mathis Rech" ]

[dependencies]
ahash = "0.7"
lru = "0.7"
crossterm = "0.21"
gfx = "0.18"
gfx_device_gl = "0.16"
ggez = "0.6"
spin_sleep = "1.0"
getopts = "0.2"
bytemuck = { version = "1.9", features = ["derive"] }
